name: CI Image Builds
on:
  push:
    branches: main
jobs:
  build-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    env:
      GHCR_PAT: ${{secrets.GHCR_PAT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Set up docker authentication
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build image
        run: |
          docker build \
            -f Dockerfile \
            -t ghcr.io/digiblink/alpine-nginx-php74-pdf:latest \
            -t ghcr.io/digiblink/alpine-nginx-php74-pdf:$SHORT_SHA \
            .
      - name: Push latest image to GHCR
        run: docker push ghcr.io/digiblink/alpine-nginx-php74-pdf:latest
      - name: Push SHORT_SHA image to GHCR
        run: docker push ghcr.io/digiblink/alpine-nginx-php74-pdf:$SHORT_SHA
