name: PR CI Image Builds
on: pull_request
jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      GHCR_PAT: ${{secrets.GHCR_PAT}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/digiblink/alpine-nginx-php74-pdf
          tags: |
            type=sha,prefix=
          flavor: |
            latest=true
            prefix=
            suffix=
          labels: |
            org.opencontainers.image.vendor=digiBlink
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
